version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: go_backend_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: go_backend
      MYSQL_USER: go_user
      MYSQL_PASSWORD: go_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
